DROP SEQUENCE SEC_IDCLIENTE;

DROP TABLE CLIENTES;

CREATE TABLE CLIENTES (
  IDCLIENTE INTEGER NOT NULL,
	NOMBRE VARCHAR2(25) NOT NULL,
	APELLIDOS VARCHAR2(75),
  FECHA_NACIMIENTO DATE,
	EMAIL VARCHAR2(75) NOT NULL UNIQUE,
	PASS VARCHAR2(75) NOT NULL,
	
	PRIMARY KEY (IDCLIENTE) );

CREATE OR REPLACE PROCEDURE INSERTAR_NUEVO_CLIENTE(
   P_NOM IN CLIENTES.NOMBRE%TYPE,
   P_APE IN CLIENTES.APELLIDOS%TYPE,
   P_FECHA_NAC IN CLIENTES.FECHA_NACIMIENTO%TYPE,
   P_EMAIL IN CLIENTES.EMAIL%TYPE,
   P_PASS IN CLIENTES.PASS%TYPE) IS
BEGIN
  INSERT INTO CLIENTES(NOMBRE,APELLIDOS,FECHA_NACIMIENTO,EMAIL,PASS)
  VALUES (P_NOM,P_APE,P_FECHA_NAC,P_EMAIL,P_PASS);
END;
/

CREATE SEQUENCE SEC_IDCLIENTE
START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE OR REPLACE TRIGGER CHECK_INSERTAR_IDCLIENTE
BEFORE INSERT ON CLIENTES
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
  SELECT SEC_IDCLIENTE.NEXTVAL INTO :NEW.IDCLIENTE FROM DUAL;
END;
/